# Generated by Django 4.2.9 on 2024-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
