# Generated by Django 4.2.9 on 2024-02-12 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_updated', models.DateTimeField(auto_now=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('require_order_prepayments', models.BooleanField(default=False)),
                ('expose_order_ratings', models.BooleanField(default=True)),
                ('allow_deliveries', models.BooleanField(default=False)),
                ('allow_pickups', models.BooleanField(default=False)),
                ('preferred_subscription_method', models.CharField(choices=[('per_order', 'Per Order'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='per_order', max_length=255)),
                ('order_surcharge_percentage', models.FloatField(default=1.0)),
                ('flat_fee', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_updated', models.DateTimeField(auto_now=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('roles', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_employees',
                'ordering': ['restaurant', 'user__first_name'],
            },
        ),
    ]
