# Generated by Django 4.2.9 on 2024-02-12 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantemployee',
            unique_together={('user', 'restaurant')},
        ),
    ]
