# Generated by Django 4.2.9 on 2024-02-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0004_alter_restaurant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='section_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_section_banners/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_cover_photos/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logos/'),
        ),
    ]
