# Generated by Django 4.2.9 on 2024-02-27 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants_app', '0005_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='extras_applicable',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='branding_configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='SectionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_updated', models.DateTimeField(auto_now=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.menusection')),
            ],
            options={
                'db_table': 'section_groups',
                'ordering': ['name'],
                'unique_together': {('name', 'section')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='section_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.sectiongroup'),
        ),
    ]
