# Generated by Django 4.2.9 on 2024-03-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0006_menuitem_discount_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menusection',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantemployee',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectiongroup',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
