# Generated by Django 4.2.9 on 2024-03-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0007_menuitem_archived_menusection_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='UG', max_length=5),
        ),
    ]
