# Generated by Django 4.2.9 on 2024-04-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0008_restaurant_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='restaurant_cover_photos/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(null=True, upload_to='restaurant_logos/'),
        ),
    ]
