# Generated by Django 4.2.9 on 2024-06-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0009_alter_restaurant_cover_photo_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
