# Generated by Django 4.2.9 on 2024-06-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0010_table_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='consider_discount_object',
            field=models.BooleanField(default=False),
        ),
    ]
