# Generated by Django 4.2.9 on 2024-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0011_menuitem_consider_discount_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menusection',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menusection',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='first_time_menu_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectiongroup',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectiongroup',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
