# Generated by Django 4.2.9 on 2024-07-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0012_menuitem_approved_menuitem_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='order_surcharge_cap_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='order_surcharge_min_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
