# Generated by Django 4.2.9 on 2024-12-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0015_menuitem_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='subscription_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_validity',
            field=models.BooleanField(default=True),
        ),
    ]
