# Generated by Django 4.2.9 on 2025-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0020_alter_table_unique_together_table_str_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningarea',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
