# Generated by Django 4.2.9 on 2025-05-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0021_diningarea_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_extras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
