# Generated by Django 4.2.9 on 2025-05-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0022_menuitem_has_extras_table_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='available',
        ),
    ]
