# Generated by Django 4.2.9 on 2026-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0026_menuitem_is_special"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="primary_price",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
