# Generated by Django 4.2.9 on 2026-03-26 21:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0027_alter_menuitem_discounted_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="flat_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=50
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="order_surcharge_cap_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=50
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="order_surcharge_min_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=50
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="order_surcharge_percentage",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("1.0"), max_digits=10
            ),
        ),
    ]
