# Generated by Django 4.2.9 on 2026-03-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0028_alter_restaurant_flat_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
