# Generated by Django 4.2.9 on 2026-03-31 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants_app", "0030_menusection_availability_menusection_schedules"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpsellConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_last_updated", models.DateTimeField(auto_now=True)),
                ("time_deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "deletion_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("vacuumed", models.BooleanField(default=False)),
                ("eod_last_date", models.DateField(db_index=True, null=True)),
                ("eod_record_date", models.DateField(db_index=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(default="You might also like", max_length=255),
                ),
                ("max_items_to_show", models.IntegerField(default=6)),
                ("hide_if_in_basket", models.BooleanField(default=True)),
                ("hide_out_of_stock", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsell_config",
                        to="restaurants_app.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "upsell_configs",
            },
        ),
        migrations.CreateModel(
            name="UpsellItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_last_updated", models.DateTimeField(auto_now=True)),
                ("time_deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "deletion_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("vacuumed", models.BooleanField(default=False)),
                ("eod_last_date", models.DateField(db_index=True, null=True)),
                ("eod_record_date", models.DateField(db_index=True, null=True)),
                ("listing_position", models.IntegerField(default=0)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsell_items",
                        to="restaurants_app.upsellconfig",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsell_entries",
                        to="restaurants_app.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "upsell_items",
                "ordering": ["listing_position"],
                "unique_together": {("config", "menu_item")},
            },
        ),
    ]
