# Generated by Django 4.2.9 on 2026-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0031_upsellconfig_upsellitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="preset_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
