# Generated by Django 4.2.9 on 2026-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0032_menuitem_tags_restaurant_preset_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
