# Generated by Django 4.2.9 on 2026-04-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0033_menuitem_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="diningarea",
            name="accessible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningarea",
            name="default_server_section",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="diningarea",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="diningarea",
            name="is_indoor",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="table",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="table",
            name="floor_height",
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name="table",
            name="floor_width",
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name="table",
            name="floor_x",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="table",
            name="floor_y",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="table",
            name="has_qr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="table",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="table",
            name="max_capacity",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="table",
            name="min_capacity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="table",
            name="qr_mode",
            field=models.CharField(
                choices=[
                    ("menu_only", "Menu Only"),
                    ("order_pay", "Order & Pay"),
                    ("order_only", "Order Only"),
                ],
                default="order_pay",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="qr_regenerated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="shape",
            field=models.CharField(
                choices=[
                    ("round", "Round"),
                    ("square", "Square"),
                    ("rectangle", "Rectangle"),
                    ("bar", "Bar"),
                ],
                default="square",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("seated", "Seated"),
                    ("bill_requested", "Bill Requested"),
                    ("dirty", "Dirty"),
                    ("out_of_service", "Out of Service"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
