# Generated by Django 4.2.9 on 2026-04-11 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants_app", "0034_diningarea_accessible_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_last_updated", models.DateTimeField(auto_now=True)),
                ("time_deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "deletion_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("vacuumed", models.BooleanField(default=False)),
                ("eod_last_date", models.DateField(db_index=True, null=True)),
                ("eod_record_date", models.DateField(db_index=True, null=True)),
                ("guest_name", models.CharField(max_length=255)),
                (
                    "guest_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("party_size", models.IntegerField(default=2)),
                ("quoted_wait_min", models.IntegerField(default=15)),
                ("quoted_wait_max", models.IntegerField(default=30)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("seated", "Seated"),
                            ("left", "Left"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("seated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants_app.restaurant",
                    ),
                ),
                (
                    "seated_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurants_app.table",
                    ),
                ),
            ],
            options={
                "db_table": "waitlist_entries",
                "ordering": ["added_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_last_updated", models.DateTimeField(auto_now=True)),
                ("time_deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "deletion_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("vacuumed", models.BooleanField(default=False)),
                ("eod_last_date", models.DateField(db_index=True, null=True)),
                ("eod_record_date", models.DateField(db_index=True, null=True)),
                ("guest_name", models.CharField(max_length=255)),
                (
                    "guest_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "guest_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_time", models.DateTimeField()),
                ("party_size", models.IntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("arrived", "Arrived"),
                            ("late", "Late"),
                            ("no_show", "No Show"),
                            ("seated", "Seated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "area_preference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("seated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants_app.restaurant",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurants_app.restaurantemployee",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurants_app.table",
                    ),
                ),
            ],
            options={
                "db_table": "reservations",
                "ordering": ["date_time"],
            },
        ),
    ]
