# Generated by Django 4.2.9 on 2026-04-13 16:17

from django.db import migrations, models
import restaurants_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0035_waitlistentry_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="branding_configuration",
            field=models.JSONField(
                default=restaurants_app.models.default_branding_configuration
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="first_time_menu_approval",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="first_time_menu_approval_decision",
            field=models.CharField(default="approve", max_length=255),
        ),
    ]
