# Generated by Django 4.2.9 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0036_alter_restaurant_branding_configuration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="calories",
            field=models.PositiveIntegerField(blank=True, help_text="Calorie count (kcal)", null=True),
        ),
    ]
