# Generated by Django 4.2.9 on 2026-05-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0043_migrate_menuitem_allergens_to_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="menu_items/thumbnails/"
            ),
        ),
    ]
