# Generated by Django 4.2.9 on 2026-05-12 12:00

import logging

from django.db import migrations


logger = logging.getLogger(__name__)


def audit_unmigrated_legacy_rows(apps, schema_editor):
    """Warn (do not block) if any MenuItem still has data in the legacy
    `tags` JSON column without a corresponding row in `menu_item_tags`.

    The 0045 data migration should have linked every legacy value to a
    RestaurantTag. This check runs immediately before the column is
    dropped so we have an audit trail in deploy logs if any rows slipped
    through.
    """
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        # The audit query relies on jsonb_* helpers. Non-Postgres
        # backends (sqlite under unit tests) skip the audit; production
        # runs on Postgres where the helpers exist.
        return
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM menu_items mi
            WHERE jsonb_typeof(mi.tags) = 'array'
              AND jsonb_array_length(mi.tags) > 0
              AND NOT EXISTS (
                  SELECT 1 FROM menu_item_tags mit
                  WHERE mit.menu_item_id = mi.id
              )
            """
        )
        unmigrated = cursor.fetchone()[0]
    if unmigrated:
        logger.warning(
            "Dropping MenuItem._legacy_tags: %s rows had legacy values "
            "with no menu_item_tags link. Data in those rows will be lost.",
            unmigrated,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0045_seed_and_backfill_restaurant_tag_catalog"),
    ]

    operations = [
        migrations.RunPython(
            audit_unmigrated_legacy_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="_legacy_tags",
        ),
    ]
