# Generated by Django 4.2.9 on 2024-02-22 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_app', '0002_order_customer_match_attempted_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
