# Generated by Django 4.2.9 on 2024-02-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_order_prepayment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_of_options',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
