# Generated by Django 4.2.9 on 2024-03-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_order_customer_email_order_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
