# Generated by Django 4.2.9 on 2024-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0007_order_archived_orderitem_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
