# Generated by Django 4.2.9 on 2024-05-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0010_order_order_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
