# Generated by Django 4.2.9 on 2024-06-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0012_order_rating_order_review_orderitem_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='block_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='block_review',
            field=models.BooleanField(default=False),
        ),
    ]
