# Generated by Django 4.2.9 on 2024-06-12 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_app', '0013_order_block_review_orderitem_block_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='block_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review_blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
