# Generated by Django 4.2.9 on 2024-06-12 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_app', '0014_orderitem_block_reason_orderitem_review_blocked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='block_reason',
            new_name='block_review_reason',
        ),
        migrations.AddField(
            model_name='order',
            name='block_review_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_review_blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='review_blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_review_blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
