# Generated by Django 4.2.9 on 2024-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0015_rename_block_reason_orderitem_block_review_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='option',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option_choice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option_cost',
            field=models.FloatField(null=True),
        ),
    ]
