# Generated by Django 4.2.9 on 2025-06-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0021_order_eod_last_date_order_eod_record_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-time_created', 'item__name']},
        ),
    ]
