# Generated by Django 4.2.9 on 2026-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0023_orderitem_unit_cost_of_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="actual_cost",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="discounted_cost",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="savings",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
