# Generated by Django 4.2.9 on 2026-03-26 21:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders_app",
            "0024_alter_order_actual_cost_alter_order_discounted_cost_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="actual_cost",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="cost_of_options",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=50
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discounted_cost",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discounted_price",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="option_cost",
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="savings",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_cost_of_options",
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
