# Generated by Django 4.2.9 on 2026-04-07 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0032_menuitem_tags_restaurant_preset_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders_app", "0026_orderitem_selected_modifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_last_updated", models.DateTimeField(auto_now=True)),
                ("time_deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "deletion_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("vacuumed", models.BooleanField(default=False)),
                ("eod_last_date", models.DateField(db_index=True, null=True)),
                ("eod_record_date", models.DateField(db_index=True, null=True)),
                ("ticket_number", models.IntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_prep", "In Prep"),
                            ("ready", "Ready"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=50,
                    ),
                ),
                ("station", models.CharField(blank=True, max_length=100, null=True)),
                ("items_count", models.PositiveIntegerField(default=0)),
                ("target_prep_minutes", models.PositiveIntegerField(default=15)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("prep_started_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_tickets",
                        to="orders_app.order",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_tickets_restaurant",
                        to="restaurants_app.restaurant",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_tickets_table",
                        to="restaurants_app.table",
                    ),
                ),
            ],
            options={
                "db_table": "kitchen_tickets",
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="KitchenTicketItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_last_updated", models.DateTimeField(auto_now=True)),
                ("time_deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "deletion_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("vacuumed", models.BooleanField(default=False)),
                ("eod_last_date", models.DateField(db_index=True, null=True)),
                ("eod_record_date", models.DateField(db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("station", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_ticket_items",
                        to="orders_app.orderitem",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_items",
                        to="orders_app.kitchenticket",
                    ),
                ),
            ],
            options={
                "db_table": "kitchen_ticket_items",
                "ordering": ["ticket", "name"],
            },
        ),
    ]
