# Generated by Django 4.2.9 on 2025-05-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysactivityconfig',
            name='eod_current_status',
        ),
        migrations.RemoveField(
            model_name='sysactivityconfig',
            name='eod_end_time',
        ),
        migrations.RemoveField(
            model_name='sysactivityconfig',
            name='eod_last_date',
        ),
        migrations.RemoveField(
            model_name='sysactivityconfig',
            name='eod_start_time',
        ),
        migrations.AlterField(
            model_name='sysactivityconfig',
            name='config_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
