# Generated by Django 4.2.9 on 2025-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_app', '0002_remove_sysactivityconfig_eod_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysactivityconfig',
            name='config_datetime_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sysactivityconfig',
            name='config_date_value',
            field=models.DateField(blank=True, null=True),
        ),
    ]
