# Generated by Django 4.2.9 on 2024-03-19 07:37

from django.db import migrations, models
import finance_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinifytransaction',
            name='transaction_status',
            field=models.CharField(db_index=True, default='initiated', max_length=255, validators=[finance_app.models.validate_transaction_status]),
        ),
    ]
