# Generated by Django 4.2.9 on 2024-03-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_alter_dinifytransaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifyaccount',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='customer_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='gross_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='manual_payment',
            field=models.BooleanField(default=False),
        ),
    ]
