# Generated by Django 4.2.9 on 2024-03-27 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_dinifyaccount_archived_dinifytransaction_archived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinifyaccount',
            old_name='actual_balance',
            new_name='momo_actual_balance',
        ),
        migrations.RenameField(
            model_name='dinifyaccount',
            old_name='available_balance',
            new_name='momo_available_balance',
        ),
        migrations.RenameField(
            model_name='dinifyaccount',
            old_name='cumulative_disbursements',
            new_name='momo_cumulative_disbursements',
        ),
        migrations.RenameField(
            model_name='dinifyaccount',
            old_name='cumulative_in',
            new_name='momo_cumulative_in',
        ),
        migrations.RenameField(
            model_name='dinifyaccount',
            old_name='cumulative_in_charges',
            new_name='momo_cumulative_in_charges',
        ),
        migrations.RenameField(
            model_name='dinifyaccount',
            old_name='cumulative_out',
            new_name='momo_cumulative_out',
        ),
        migrations.RenameField(
            model_name='dinifyaccount',
            old_name='cumulative_out_charges',
            new_name='momo_cumulative_out_charges',
        ),
        migrations.RenameField(
            model_name='dinifyaccount',
            old_name='cumulative_refunds',
            new_name='momo_cumulative_refunds',
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='card_actual_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='card_available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='card_cumulative_disbursements',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='card_cumulative_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='card_cumulative_in_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='card_cumulative_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='card_cumulative_out_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='card_cumulative_refunds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='cash_actual_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='cash_available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='cash_cumulative_disbursements',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='cash_cumulative_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='cash_cumulative_in_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='cash_cumulative_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='cash_cumulative_out_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='cash_cumulative_refunds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='processed',
            field=models.CharField(default='pending', max_length=25),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='revenue_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='revenue_collection_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='revenue_initiation_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_app.dinifytransaction'),
        ),
    ]
