# Generated by Django 4.2.9 on 2024-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_dinifytransaction_payment_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifytransaction',
            name='manual_payment_details',
            field=models.JSONField(null=True),
        ),
    ]
