# Generated by Django 4.2.9 on 2024-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0010_dinifytransaction_source_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifytransaction',
            name='processing_status',
            field=models.CharField(db_index=True, default='pending', max_length=255),
        ),
    ]
