# Generated by Django 4.2.9 on 2024-12-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0011_dinifytransaction_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinifytransaction',
            name='revenue_collection_timestamp',
        ),
        migrations.RemoveField(
            model_name='dinifytransaction',
            name='revenue_initiation_transaction',
        ),
        migrations.RemoveField(
            model_name='dinifytransaction',
            name='source_order_payment',
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='parent_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_parent_transaction', to='finance_app.dinifytransaction'),
        ),
        migrations.AlterField(
            model_name='dinifytransaction',
            name='revenue_collected',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
