# Generated by Django 4.2.9 on 2024-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0013_dinifytransaction_amount_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifytransaction',
            name='transaction_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
