# Generated by Django 4.2.9 on 2024-12-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0015_bankaccountrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinifytransaction',
            name='aggregator_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
